# Code generated by protoc-gen-crystal. DO NOT EDIT.
# source: grpc/health/v1/health.proto

require "proto"

module Grpc
  module Health
    module V1
      class HealthCheckRequest
        include Proto::Message

        property service : String = ""

        def self.decode_partial(io : IO) : self
          msg = new
          reader = Proto::Wire::Reader.new(io)
          while tag = reader.read_tag
            fn, wt = tag
            case fn
            when 1
              reader.expect_wire_type!(1, wt, Proto::WireType::LENGTH_DELIMITED)
              msg.service = reader.read_string
            else
              msg.capture_unknown_field(reader.read_unknown_field(fn, wt))
            end
          end
          msg
        end

        def self.decode(io : IO) : self
          msg = decode_partial(io)
          msg
        end

        def encode_partial(io : IO) : Nil
          w = Proto::Wire::Writer.new(io)
          if !service.empty?
            w.write_tag(1, Proto::WireType::LENGTH_DELIMITED)
            w.write_string(service)
          end
          write_unknown_fields(w)
        end

        def encode(io : IO) : Nil
          encode_partial(io)
        end

        def ==(other : self) : Bool
          return false unless service == other.service
          return false unless unknown_fields == other.unknown_fields
          true
        end
      end

      class HealthCheckResponse
        include Proto::Message

        enum ServingStatus : Int32
          UNKNOWN         = 0
          SERVING         = 1
          NOT_SERVING     = 2
          SERVICE_UNKNOWN = 3

          def self.from_raw?(raw : Int32) : self?
            case raw
            when 0 then UNKNOWN
            when 1 then SERVING
            when 2 then NOT_SERVING
            when 3 then SERVICE_UNKNOWN
            end
          end
        end

        property status : Proto::OpenEnum(HealthCheckResponse::ServingStatus) = Proto::OpenEnum(HealthCheckResponse::ServingStatus).new(0)

        def self.decode_partial(io : IO) : self
          msg = new
          reader = Proto::Wire::Reader.new(io)
          while tag = reader.read_tag
            fn, wt = tag
            case fn
            when 1
              reader.expect_wire_type!(1, wt, Proto::WireType::VARINT)
              _raw_u64 = reader.read_uint64
              _raw = Proto::Wire::Reader.int32_from_varint(_raw_u64)
              msg.status = Proto::OpenEnum(HealthCheckResponse::ServingStatus).new(_raw)
            else
              msg.capture_unknown_field(reader.read_unknown_field(fn, wt))
            end
          end
          msg
        end

        def self.decode(io : IO) : self
          msg = decode_partial(io)
          msg
        end

        def encode_partial(io : IO) : Nil
          w = Proto::Wire::Writer.new(io)
          if status.raw != 0
            w.write_tag(1, Proto::WireType::VARINT)
            w.write_int32(status.raw)
          end
          write_unknown_fields(w)
        end

        def encode(io : IO) : Nil
          encode_partial(io)
        end

        def ==(other : self) : Bool
          return false unless status == other.status
          return false unless unknown_fields == other.unknown_fields
          true
        end
      end

      class HealthListRequest
        include Proto::Message

        def self.decode_partial(io : IO) : self
          msg = new
          reader = Proto::Wire::Reader.new(io)
          while tag = reader.read_tag
            fn, wt = tag
            case fn
            else
              msg.capture_unknown_field(reader.read_unknown_field(fn, wt))
            end
          end
          msg
        end

        def self.decode(io : IO) : self
          msg = decode_partial(io)
          msg
        end

        def encode_partial(io : IO) : Nil
          w = Proto::Wire::Writer.new(io)
          write_unknown_fields(w)
        end

        def encode(io : IO) : Nil
          encode_partial(io)
        end

        def ==(other : self) : Bool
          return false unless unknown_fields == other.unknown_fields
          true
        end
      end

      class HealthListResponse
        include Proto::Message

        class StatusesEntry
          include Proto::Message

          property key : String = ""
          property value : HealthCheckResponse? = nil

          def has_value? : Bool
            !value.nil?
          end

          def clear_value : Nil
            self.value = nil
          end

          def validate_required! : Nil
          end

          def validate_required_deep! : Nil
            validate_required!
            value.try &.validate_required_deep!
          end

          def self.decode_partial(io : IO) : self
            msg = new
            reader = Proto::Wire::Reader.new(io)
            while tag = reader.read_tag
              fn, wt = tag
              case fn
              when 1
                reader.expect_wire_type!(1, wt, Proto::WireType::LENGTH_DELIMITED)
                msg.key = reader.read_string
              when 2
                msg.value = reader.read_embedded(2, wt) { |sub| HealthCheckResponse.decode_partial(sub) }
              else
                msg.capture_unknown_field(reader.read_unknown_field(fn, wt))
              end
            end
            msg
          end

          def self.decode(io : IO) : self
            msg = decode_partial(io)
            msg.validate_required_deep!
            msg
          end

          def encode_partial(io : IO) : Nil
            w = Proto::Wire::Writer.new(io)
            if !key.empty?
              w.write_tag(1, Proto::WireType::LENGTH_DELIMITED)
              w.write_string(key)
            end
            if _v = value
              w.write_embedded(2) { |sub| _v.encode_partial(sub) }
            end
            write_unknown_fields(w)
          end

          def encode(io : IO) : Nil
            validate_required_deep!
            encode_partial(io)
          end

          def ==(other : self) : Bool
            return false unless key == other.key
            return false unless value == other.value
            return false unless unknown_fields == other.unknown_fields
            true
          end
        end

        property statuses : Hash(String, HealthCheckResponse) = {} of String => HealthCheckResponse

        def validate_required! : Nil
        end

        def validate_required_deep! : Nil
          validate_required!
          statuses.each_value do |value|
            value.validate_required_deep!
          end
        end

        def self.decode_partial(io : IO) : self
          msg = new
          reader = Proto::Wire::Reader.new(io)
          while tag = reader.read_tag
            fn, wt = tag
            case fn
            when 1
              entry = reader.read_embedded(1, wt) { |sub| HealthListResponse::StatusesEntry.decode_partial(sub) }
              if value = entry.value
                msg.statuses[entry.key] = value
              end
            else
              msg.capture_unknown_field(reader.read_unknown_field(fn, wt))
            end
          end
          msg
        end

        def self.decode(io : IO) : self
          msg = decode_partial(io)
          msg.validate_required_deep!
          msg
        end

        def encode_partial(io : IO) : Nil
          w = Proto::Wire::Writer.new(io)
          statuses.each do |k, v|
            entry = HealthListResponse::StatusesEntry.new
            entry.key = k
            entry.value = v
            w.write_embedded(1) { |sub| entry.encode_partial(sub) }
          end
          write_unknown_fields(w)
        end

        def encode(io : IO) : Nil
          validate_required_deep!
          encode_partial(io)
        end

        def ==(other : self) : Bool
          return false unless statuses == other.statuses
          return false unless unknown_fields == other.unknown_fields
          true
        end
      end

      module Health
        METHODS = [
          {
            name:             "Check",
            request_type:     ".grpc.health.v1.HealthCheckRequest",
            response_type:    ".grpc.health.v1.HealthCheckResponse",
            client_streaming: false,
            server_streaming: false,
            path:             "/grpc.health.v1.Health/Check",
          },
          {
            name:             "List",
            request_type:     ".grpc.health.v1.HealthListRequest",
            response_type:    ".grpc.health.v1.HealthListResponse",
            client_streaming: false,
            server_streaming: false,
            path:             "/grpc.health.v1.Health/List",
          },
          {
            name:             "Watch",
            request_type:     ".grpc.health.v1.HealthCheckRequest",
            response_type:    ".grpc.health.v1.HealthCheckResponse",
            client_streaming: false,
            server_streaming: true,
            path:             "/grpc.health.v1.Health/Watch",
          },
        ] of NamedTuple(name: String, request_type: String, response_type: String, client_streaming: Bool, server_streaming: Bool, path: String)
      end
    end
  end
end
